twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/src/UserInterface/Web/Backoffice/Twig': Backoffice
        '%kernel.project_dir%/src/UserInterface/Web/Pub/Twig': Pub

when@test:
    twig:
        strict_variables: true
